# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-07 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170804_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='fault_address',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='moment',
            name='fault_describe',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='moment',
            name='fault_title',
            field=models.CharField(max_length=20),
        ),
    ]
