# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-08 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170807_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagonos',
            fields=[
                ('moment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Moment')),
                ('dgs_hosttype', models.IntegerField()),
                ('dgs_host', models.GenericIPAddressField()),
                ('dgs_hostrange', models.CharField(max_length=50)),
                ('dgs_codeN', models.IntegerField()),
                ('dgs_codeP', models.IntegerField()),
                ('dgs_codeL', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('C', 'C'), ('C++', 'C++'), ('Php', 'Php')], default=('Python', 'Python'), max_length=20)),
                ('dgs_codeA', models.CharField(max_length=30)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
