# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-08 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_diagonos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagonos',
            name='dgs_hosttype',
            field=models.IntegerField(default=1),
        ),
    ]
