# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-08 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170808_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagonos',
            name='dgs_codeN',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='diagonos',
            name='dgs_codeP',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='diagonos',
            name='dgs_hostrange',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='diagonos',
            name='dgs_hosttype',
            field=models.IntegerField(choices=[(0, '\u5355\u4e2a'), (1, '\u591a\u4e2a')], default=(0, '\u5355\u4e2a')),
        ),
    ]
