# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-08 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170808_0745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moment',
            options={'ordering': ('-pub_date',)},
        ),
    ]
