# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-12 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170808_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagonos',
            name='dgs_hosttype',
            field=models.IntegerField(choices=[('0', '\u5355\u4e2a'), ('1', '\u591a\u4e2a')], default=('0', '\u5355\u4e2a')),
        ),
    ]
