# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-22 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chost',
            fields=[
                ('hostId', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('hostName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='chostgroups',
            fields=[
                ('hostgroupsId', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('hostgrouspName', models.CharField(max_length=50)),
            ],
        ),
    ]
