# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-23 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180122_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='ctemplates',
            fields=[
                ('templateId', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('templateName', models.CharField(max_length=50)),
            ],
        ),
    ]
