# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-24 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180123_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='cinterface',
            fields=[
                ('interfaceId', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('hostId', models.IntegerField(max_length=8)),
            ],
        ),
    ]
