# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-31 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_citem_citemgroups_ctrigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citem',
            name='itemId',
            field=models.IntegerField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
