# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-24 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180131_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='caction',
            fields=[
                ('actionId', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('actionName', models.CharField(max_length=255)),
                ('actionStatus', models.IntegerField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='crecovery',
            fields=[
                ('recoveryId', models.AutoField(primary_key=True, serialize=False)),
                ('recoveryTime', models.CharField(max_length=255)),
                ('recoveryDate', models.CharField(max_length=255)),
                ('actionName', models.CharField(max_length=255)),
                ('triggerStatus', models.CharField(max_length=50)),
                ('triggerSeverity', models.CharField(max_length=50)),
                ('triggerName', models.CharField(max_length=255)),
                ('itemValues', models.CharField(max_length=50)),
                ('eventId', models.IntegerField(max_length=10)),
                ('eventValue', models.IntegerField(max_length=10)),
                ('eventStatus', models.CharField(max_length=10)),
                ('originaleventID', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='chost',
            name='hostStatus',
            field=models.IntegerField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cinterface',
            name='hostIp',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chost',
            name='hostName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='chostgroups',
            name='hostgroupsName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cinterface',
            name='hostId',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='citem',
            name='hostId',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='citem',
            name='itemId',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='citem',
            name='templateId',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='citemgroups',
            name='hostId',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='citemgroups',
            name='itemgroupsId',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='citemgroups',
            name='itemgroupsName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ctemplates',
            name='templatesName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ctrigger',
            name='itemId',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ctrigger',
            name='triggerId',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ctrigger',
            name='triggerPriority',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ctrigger',
            name='triggerValue',
            field=models.IntegerField(max_length=10),
        ),
    ]
