# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-15 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180324_0448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crecovery',
            name='recoveryId',
        ),
        migrations.AlterField(
            model_name='crecovery',
            name='eventId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
