# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-15 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180415_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='crecovery',
            name='returnValue',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
